<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ page import = "java.sql.*" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Database SQL Load</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database SQL Load</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "homework1";
            String schema = "ROOT";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname, "root", "root");
            Statement stmt = con.createStatement();
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{
                //Customers (ID,EMAIL,PASSWORD,USRNAME)
                "INSERT INTO " + schema + ".CUSTOMER VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'aaa@gmail.com','password', 'banana')",
                "INSERT INTO " + schema + ".CUSTOMER VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'aaa2@gmail.com','password2', 'banana2')",
                "INSERT INTO " + schema + ".CUSTOMER VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'sob@gmail.com','sob','sob')",
                //Products (ID, name, nutritionalinformation, servicetime, type)
                "INSERT INTO " + schema + ".PRODUCT VALUES (NEXT VALUE FOR PRODUCT_GEN, 'Water', '0 kcal', 0, 'Drink')",
                "INSERT INTO " + schema + ".PRODUCT VALUES (NEXT VALUE FOR PRODUCT_GEN, 'Nestea', '106 kcal', 0, 'Drink')",
                "INSERT INTO " + schema + ".PRODUCT VALUES (NEXT VALUE FOR PRODUCT_GEN, 'Espresso', '50 kcal', 5, 'Coffee')",
                "INSERT INTO " + schema + ".PRODUCT VALUES (NEXT VALUE FOR PRODUCT_GEN, 'Black coffee', '50 kcal', 5, 'Coffee')",
                "INSERT INTO " + schema + ".PRODUCT VALUES (NEXT VALUE FOR PRODUCT_GEN, 'Mocha', '50 kcal', 5, 'Coffee')",
                //ProductSizes (price, size, productid)
                "INSERT INTO " + schema + ".PRODUCT_PRICESLIST VALUES (0.99, 'Small', 1)",
                "INSERT INTO " + schema + ".PRODUCT_PRICESLIST VALUES (1.50, 'Medium', 1)",
                "INSERT INTO " + schema + ".PRODUCT_PRICESLIST VALUES (1.99, 'Large', 1)",
                "INSERT INTO " + schema + ".PRODUCT_PRICESLIST VALUES (1.99, '330 cl', 2)",
                "INSERT INTO " + schema + ".PRODUCT_PRICESLIST VALUES (0.99, 'Small', 3)",
                "INSERT INTO " + schema + ".PRODUCT_PRICESLIST VALUES (1.50, 'Medium', 3)",
                "INSERT INTO " + schema + ".PRODUCT_PRICESLIST VALUES (1.99, 'Large', 3)",
                "INSERT INTO " + schema + ".PRODUCT_PRICESLIST VALUES (0.99, 'Small', 4)",
                "INSERT INTO " + schema + ".PRODUCT_PRICESLIST VALUES (1.50, 'Medium', 4)",
                "INSERT INTO " + schema + ".PRODUCT_PRICESLIST VALUES (1.99, 'Large', 4)",
                "INSERT INTO " + schema + ".PRODUCT_PRICESLIST VALUES (0.99, 'Small', 5)",
                "INSERT INTO " + schema + ".PRODUCT_PRICESLIST VALUES (1.50, 'Medium', 5)",
                "INSERT INTO " + schema + ".PRODUCT_PRICESLIST VALUES (1.99, 'Large', 5)",
                
                //Store (ID, cityName, latitude, longitude)
                "INSERT INTO " + schema + ".STORE VALUES (NEXT VALUE FOR STORE_GEN, 'Tarragona', '41.119359', '1.245648')",
                //Sale (ID, custId, storeid)
                "INSERT INTO " + schema + ".SALE VALUES (NEXT VALUE FOR SALE_GEN, 1, 1)",
                //PRODUCTSALE (ID, product_size, quantity, sweeteners, productId, saleId)
                "INSERT INTO " + schema + ".PRODUCTSALE VALUES (NEXT VALUE FOR PRODUCTSALE_GEN, 'S', 2, '', 1, 1)",
                "INSERT INTO " + schema + ".PRODUCTSALE VALUES (NEXT VALUE FOR PRODUCTSALE_GEN, 'M', 1, 'azucar', 1, 1)",
                "INSERT INTO " + schema + ".PRODUCTSALE VALUES (NEXT VALUE FOR PRODUCTSALE_GEN, 'Short', 1, 'sacarina', 2, 1)",
                //PRODUCT_STORE (storeId, productId)
                "INSERT INTO " + schema + ".PRODUCT_STORE VALUES (1, 1)",
                "INSERT INTO " + schema + ".PRODUCT_STORE VALUES (1, 2)",
                "INSERT INTO " + schema + ".PRODUCT_STORE VALUES (1, 3)",
                "INSERT INTO " + schema + ".PRODUCT_STORE VALUES (1, 4)",
                "INSERT INTO " + schema + ".PRODUCT_STORE VALUES (1, 5)",
                //Secured credentials
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'sob', 'sob')"
            };
            for (String datum : data) {
                if (stmt.executeUpdate(datum)<=0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>
